language: android

jdk:
    - oraclejdk17

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install Android SDK tools 25.1.x (x = 6 right now)
    - android-34
    - add-on
    - extra

sudo: false

before_install:
# http://stackoverflow.com/questions/33820638/travis-yml-gradlew-permission-denied
# must execute
# git update-index --chmod=+x gradlew
# instead of 
# - chmod +x gradlew
  - yes | sdkmanager "platforms;android-23"
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "platforms;android-29"
  - yes | sdkmanager "platforms;android-34"

script:
  - jdk_switcher use oraclejdk17
  - ./gradlew assemble test
